# Generated by Django 5.2.11 on 2026-04-14 12:06

import datetime
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, default='', max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('next_check_in_at', models.TimeField(default=datetime.time(20, 0))),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CareProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('emergency_contact', models.CharField(blank=True, max_length=20)),
                ('avatar_seed', models.PositiveSmallIntegerField(default=0)),
                ('avatar_uri', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('location_enabled', models.BooleanField(default=True)),
                ('microphone_enabled', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('precise_location_enabled', models.BooleanField(default=True)),
                ('background_refresh_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_profile', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='familycare_api.family')),
            ],
            options={
                'ordering': ['full_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FamilyInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relation', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('PENDING_ACCEPTANCE', 'Pending acceptance'), ('WAITING_INSTALL', 'Waiting install'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined')], default='WAITING_INSTALL', max_length=24)),
                ('is_platform_user', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='familycare_api.family')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to='familycare_api.careprofile')),
                ('platform_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_invitations', to='familycare_api.careprofile')),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AppNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.CharField(max_length=400)),
                ('category', models.CharField(choices=[('INVITE', 'Invite'), ('SAFETY', 'Safety'), ('CRIME', 'Crime'), ('SYSTEM', 'System')], max_length=12)),
                ('is_read', models.BooleanField(default=False)),
                ('action_label', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='familycare_api.family')),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='familycare_api.familyinvitation')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('relation', models.CharField(max_length=60)),
                ('age', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default=0, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('place_label', models.CharField(blank=True, max_length=120)),
                ('battery_level', models.PositiveSmallIntegerField(default=100)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('heart_rate', models.PositiveSmallIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('SAFE', 'Safe'), ('MOVING', 'Moving'), ('NEEDS_ATTENTION', 'Needs attention')], default='SAFE', max_length=24)),
                ('note', models.TextField(blank=True)),
                ('safe_zone', models.CharField(blank=True, max_length=120)),
                ('schedule_label', models.CharField(blank=True, max_length=120)),
                ('avatar_seed', models.PositiveSmallIntegerField(default=0)),
                ('avatar_uri', models.CharField(blank=True, max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='familycare_api.family')),
                ('linked_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_members', to='familycare_api.careprofile')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ActivityFeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('subtitle', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEUTRAL', 'Neutral'), ('WARNING', 'Warning')], default='NEUTRAL', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_items', to='familycare_api.family')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_items', to='familycare_api.familymember')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('place_label', models.CharField(blank=True, max_length=120)),
                ('battery_level', models.PositiveSmallIntegerField(default=100)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('heart_rate', models.PositiveSmallIntegerField(default=0)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='familycare_api.familymember')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SosAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RESOLVED', 'Resolved')], default='ACTIVE', max_length=12)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to='familycare_api.family')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to='familycare_api.familymember')),
            ],
            options={
                'ordering': ['-triggered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SosDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('CALLING', 'Calling'), ('NOTIFIED', 'Notified')], default='CALLING', max_length=12)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='familycare_api.sosalert')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_deliveries', to='familycare_api.familymember')),
            ],
            options={
                'ordering': ['member_id'],
            },
        ),
        migrations.CreateModel(
            name='TrustedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.PositiveIntegerField(default=200)),
                ('kind', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_places', to='familycare_api.family')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(fields=('family', 'phone'), name='family_member_phone_unique'),
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(fields=('family', 'linked_profile'), name='family_linked_profile_unique'),
        ),
        migrations.AddConstraint(
            model_name='sosdelivery',
            constraint=models.UniqueConstraint(fields=('alert', 'member'), name='sos_delivery_unique_member'),
        ),
    ]
